### ISSUE TITLE
build之后，在dist文件夹里打开index.html显示空白的页面

### ISSUE THREAD

**Issue by Godi13** [dvajs/dva-example-user-dashboard#1]
你好，本人前端新手，这两天研究了下`dva`，感觉非常棒，准备用来做公司的管理系统试一试。但是遇到了下面这个问题：

`npm start` 之后的调试都没有问题，但是`npm run build`后，我理解的是打开`index.html`文件应该显示跟`npm start`时一样的页面，可是我这边一片空白，在Network里看3个文件也都在，不知道为什么？

node 7.0.0
roadhog 0.2.3

**Comment by sorrycc** [comment]
排查了下，是部署的问题，是因为路由没有匹配到。

解决有两种方案：

1. history 用 hashHistory，在 `src/index.js` 里把 `history: browserHistory` 的配置去掉即可
2. 部署到一台服务器上，使得访问根目录能访问到 index.html，比如 http://a.com/
