### ISSUE TITLE
列表获取的id，如果过长会这样：842996249664786432 -- >842996249664786400

### ISSUE THREAD

**Issue by lihua123569** [dvajs/dva-example-user-dashboard#10]
id过长会自定截取变为00
export default async function request(url, options) {
  console.log('opotions:'+options);
  const response = await fetch(url, options);

/*console.log(response);*/
  checkStatus(response);

  const data = await response.json();
 
  const ret = {
    data,
    headers: {},
  };

  if (response.headers.get('x-total-count')) {
    ret.headers['x-total-count'] = response.headers.get('x-total-count');
  }
console.log("ret:"+ret);
  return ret;
}

request.js里面的方法，  列表查询：const data = await response.json();这句获取的id如果超过16位，比如18位，后两位就会变成00（如：842996249664786432 -- >842996249664786400）
不知道啥情况？？

**Comment by sorrycc** [comment]
感觉也这个库无关。。

**Comment by lihua123569** [comment]
我验证了，就是后台类型问题，ArrayList<User> list = new ArrayList<User>();
User里面的id是long类型，及时 toString 返回json。到页面也会变，好像是长度限制了，long改成string就没事。fetch能在前端设置吗，比如让它不限制长度
