### ISSUE TITLE
run build打包后，页面空白

### ISSUE THREAD

**Issue by jojoLockLock** [dvajs/dva-example-user-dashboard#13]
跑npm start的时候没问题，但是打包后加载，页面是空白的，也没有报错。
自己试了一下，发现是路由按需加载的require里并没有执行，网上找了方法，说是ES6的写法 要加.default，但是我自己试了，没有效果。

**Comment by sorrycc** [comment]
不要用 `file://` 协议访问，用 `http://` 协议访问。

**Comment by jojoLockLock** [comment]
是的，用了http：// ，但是还是不行，我自己重新写一个就可以了，找不到原因。
另外有个问题就是打包后 的路由文件前面都有个 1. 2. 之类的前缀，请问下这个在哪里可以修改吗？
