### ISSUE TITLE
Failed to start the server, since you have enabled dllPlugin, but have not run `roadhog buildDll` before `roadhog server`.

### ISSUE THREAD

**Issue by allan2coder** [dvajs/dva-example-user-dashboard#19]
when i run "npm start",
```
Failed to start the server, since you have enabled dllPlugin, but have not run `roadhog buildDll` before `roadhog server`.
```

![qq 20170509154231](https://cloud.githubusercontent.com/assets/14307551/25842046/16587088-34d5-11e7-9ca7-89dbb5f0ba5f.jpg)

**Comment by toshcn** [comment]
linux mint18.1 
node 6.10.3

Failed to start the server, since you have enabled dllPlugin, but have not run `roadhog buildDll` before `roadhog server`.

**Comment by allan2coder** [comment]
@toshcn wtf？

**Comment by allan2coder** [comment]
@toshcn I mean how to solve it?

**Comment by toshcn** [comment]
I question has solve

1, delete package.json 6 line "build:dll": "roadhog buildDll",
2, delete src/index.html 13 line <script src="roadhog.dll.js"></script>
3, delete .roadhogrc 31-40 line
"dllPlugin": {
    "exclude": [
      "babel-runtime"
    ],
    "include": [
      "dva/router",
      "dva/saga",
      "dva/fetch"
    ]
  }

delete the dir  node_modules 
reinstall       npm install
than   npm start

ok

**Comment by blackmatch** [comment]
check this PR. https://github.com/dvajs/dva-example-user-dashboard/pull/21

**Comment by miuchan** [comment]
@toshcn @blackmatch seems it's not a bug, the plugin is for accelerating the building process, just run `npm run build:dll` should solve this ploblem, at least works for me.

**Comment by duwei54** [comment]
1.npm i roadhog -g
2.roadhog build
3.npm start

**Comment by Blackgan3** [comment]
1. npm i
2. npm run build:dll
3. npm start

**Comment by MikeDGitHub** [comment]
![image](https://user-images.githubusercontent.com/21699169/40174303-45532bb4-5a07-11e8-90bc-98c0937bafb3.png)
