### ISSUE TITLE
下载完之后 NPM  START 运行不起来

### ISSUE THREAD

**Issue by z253573760** [dvajs/dva-example-user-dashboard#24]
终端提示信息如下 
G:\dva-example-user-dashboard-master>npm start

> @ start G:\dva-example-user-dashboard-master
> roadhog server

Failed to start the server, since you have enabled dllPlugin, but have not run `
roadhog buildDll` before `roadhog server`.

**Comment by cheneddie** [comment]
到package.json增加
`"prestart": "npm run build:dll",`
like 
`"scripts": { 
    "prestart": "npm run build:dll", ...
`
