### ISSUE TITLE
roadhog build的问题

### ISSUE THREAD

**Issue by liysw** [dvajs/dva-example-user-dashboard#3]
这个项目拉下来后，没有改动，运行 npm install，再运行npm run build，把dist文件夹拷贝到apache服务下后，浏览这个index.html，发现页面是空白的。
npm start 是可以看到demo效果的

**Comment by sorrycc** [comment]
看下有没有报错。

**Comment by sorrycc** [comment]
是放到 apache 的根目录吗? (访问时不加路径)

**Comment by liysw** [comment]
还真的是，生成时候的配置路径与实际的路径不一致。多谢多谢

**Comment by liysw** [comment]
还真的是，生成时候的配置路径与实际的路径不一致。多谢多谢

**Comment by JustYJQ** [comment]
@sorrycc build 之后dist文件夹中的文件只能放到apache 的根目录？如何放到其他目录
