### ISSUE TITLE
问个目录相关的问题

### ISSUE THREAD

**Issue by Alex1990** [dvajs/dva-example-user-dashboard#4]
和 dva/React 相关的，假如下面场景：

有一个页面（Route Component），显示用户列表，然后有查看详情功能，点击列表项的“详情”按钮，就会出现一个弹层，弹层显示详情，详情是单独一个组件。

这样有两个文件：

```
UserList.jsx
UserDetail.jsx
```

假如`UserList.jsx`放到`routes`目录，那么`UserDetail.jsx`放到哪里呢？这个文件只在这里使用，我会放在`components`目录，但是有人问我“和`UserList.jsx`放到一起不是更合理一些，因为功能相关。

**Comment by ChrisFan** [comment]
- Routes
  - UserListPage.js
- Components
  - UserList
  - UserDetailModal

UserListPage 中引入 UserList & UserDetailModal，统一管理这两个模块，这样 UserList 也比较容易复用，比如在权限页面，需要展示某个角色的 UserList，只要传递相关的数据给 UserList 可以了；而不用 UserList 自己去 connect.

当然，如果项目比较简单，甚至不需要 Routes，在 Components 中按照自己的需要 connect 就可以了。
