### ISSUE TITLE
roadhog.dll.js:1 Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by joriewong** [dvajs/dva-example-user-dashboard#49]
npm start的时候其他一切正常，但是控制台报这个错
![image](https://user-images.githubusercontent.com/11408040/34375535-f9ec3ed0-eb21-11e7-8d79-59858c72d13e.png)

**Comment by xuxiao415** [comment]
@joriewong 问题解决了吗？我的项目也遇到了该问题

**Comment by joriewong** [comment]
you can choose this one
https://github.com/dvajs/dva/tree/master/packages/dva-example-user-dashboard

**Comment by joriewong** [comment]
可能是版本问题
