### ISSUE TITLE
path为二级路由时，页面不渲染问题

### ISSUE THREAD

**Issue by pmg1989** [dvajs/dva-example-user-dashboard#5]
@sorrycc ，请问下，我在你的demo里，router.js文件里 path：users的路径下新建了个childRoutes path：add，为什么页面不渲染这个路径的组件，却还是渲染users组件呢？
![image](https://cloud.githubusercontent.com/assets/13361827/22627118/8326490a-ebf7-11e6-9b1b-a58299f7382b.png)

![image](https://cloud.githubusercontent.com/assets/13361827/22627131/d8ed0464-ebf7-11e6-93a7-586eda4966ce.png)

**Comment by pmg1989** [comment]
我访问 http://localhost:8000/users/add 路由时，刷新是能找到路径的，但它还是渲染的users页面，
另外我调整了下index.html
<script src="/index.js"></script>
才可以，不知道是不是还需要配置哪里呢？

**Comment by sorrycc** [comment]
确实是应该写成 `/index.js`。
